apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: mydpapp
    type: front-end
  name: myapp-deployment
spec: 
  replicas: 3
  selector: 
    matchLabels:
      app: mydpapp
  template: 
    metadata: 
      labels: 
        app: mydpapp
      name: mydpapp-pod
    spec: 
      containers: 
        - 
          image: nginx
          name: nginx-container
