apiVersion: v1
kind: Deployment
metadata: 
  name: myapp-deployment
  labels:
    app: mydpapp
    type: front-end

spec:
  template:
    metadata:
      name: mydpapp-pod
      labels:
        app: mydpapp
    spec:
      containers:
        name: nginx-container
        image: nginx

  replicas: 3

  selector:
    matchLabels:
      app:mydpapp